set $workspace1 "1 󰙯 "
set $workspace2 "2"
set $workspace3 "3"
set $workspace4 "4"
set $workspace4 "5"
set $workspace4 "6"
set $workspace4 "7"
set $workspace8 "8 󰇮"
set $workspace9 "9"
set $workspace10 "10  "

assign [class="discord"] $workspace1
assign [class="thunderbird"] $workspace8
for_window [class="Spotify"] move to workspace $workspace10

workspace_auto_back_and_forth yes
