#!/bin/bash

aconfmgr apply
echo "Aconfmgr apply successful."

quickshell_path="$HOME/.config/quickshell"
sudo ln -sf "$quickshell_path" /etc/greetd
echo "Symlink greetd quickshell config successful."

path="$quickshell_path"
while [[ "$path" != "/" ]]; do
    sudo chmod o+x "$path"
    path=$(dirname "$path")
done
sudo mkdir -p /var/lib/greeter
sudo chown greeter:greeter /var/lib/greeter
sudo usermod -d /var/lib/greeter greeter
echo "Created home directory and granted correct permissions for greeter user."

if bw login --check &>/dev/null; then
  export BW_SESSION=$(bw unlock --raw)
else
  export BW_SESSION=$(bw login --raw)
fi
bw get notes "Secrets.qml" --session $BW_SESSION > "$HOME/.config/quickshell/Secrets.qml"
bw lock
echo "Setting up secrets successful."

gsettings set org.gnome.desktop.interface gtk-theme 'Fluent-Dark'
gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
echo "Setup gtk settings successful."

echo "Bootstrap complete"
