(deftheme duskfox
  "Created 2024-02-15.")

(deftheme duskfox "Created 2024-02-15.")

(custom-theme-set-faces
 'duskfox
 '(default ((t (:family "FiraMono Nerd Font" :foundry "CTDB" :width normal :height 113 :weight medium :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#e0def4" :background "#232136"))))
 '(cursor ((t (:background "#e0def4"))))
 '(fixed-pitch ((t (:family "FiraMono Nerd Font" :foundry "CTDB" :width normal :height 110 :weight medium :slant normal))))
 '(variable-pitch ((t (:family "Roboto" :foundry "GOOG" :width normal :height 120 :weight medium :slant normal))))
 '(escape-glyph ((t (:foreground "#9ccfd8"))))
 '(homoglyph ((t (:foreground "#9ccfd8"))))
 '(minibuffer-prompt ((t (:foreground "#9ccfd8"))))
 '(highlight ((t (:background "#569fba"))))
 '(region ((t (:extend t :background "#569fba" :foreground "#e0def4"))))
 '(shadow ((t (:foreground "#a3be8c"))))
 '(secondary-selection ((t (:extend t :background "#f6c177"))))
 '(trailing-whitespace ((t (:background "#eb6f92"))))
 '(font-lock-builtin-face ((t (:foreground "#c4a7e7"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#a6dae3"))))
 '(font-lock-comment-face ((t (:foreground "#a6dae3"))))
 '(font-lock-constant-face ((t (:foreground "#b1d196"))))
 '(font-lock-function-name-face ((t (:foreground "#65b1cd"))))
 '(font-lock-keyword-face ((t (:foreground "#ccb1ed"))))
 '(font-lock-string-face ((t (:foreground "#f9cb8c"))))
 '(font-lock-type-face ((t (:foreground "#f083a2"))))
 '(font-lock-variable-name-face ((t (:foreground "#eb98c3"))))
 '(font-lock-warning-face ((t (:foreground "#f083a2" :weight bold))))
 '(button ((t (:underline t))))
 '(link ((t (:underline t :foreground "#65b1cd"))))
 '(link-visited ((t (:underline t :foreground "#569fba"))))
 '(fringe ((t (:background "#232136"))))
 '(header-line ((t (:background "#393552" :foreground "#e0def4"))))
 '(tooltip ((t (:foreground "#232136" :background "#e0def4"))))
 '(mode-line ((t (:background "#393552" :foreground "#e0def4" :box nil))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width (2 . 2) :color "#569fba" :style released-button)))))
 '(mode-line-inactive ((t (:background "#232136" :foreground "#47407d" :box nil))))
 '(isearch ((t (:foreground "#232136" :background "#f9cb8c"))))
 '(isearch-fail ((t (:background "#eb6f92"))))
 '(lazy-highlight ((t (:background "#9ccfd8"))))
 '(match ((t (:background "#65b1cd"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 )

(provide-theme 'duskfox)
