# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = systemctl --user start hyprpolkitagent
exec-once = vesktop & spotify & thunderbird & hyprpaper & dunst & bitwarden-desktop & hypridle & hyprsunset & udiskie
exec-once = quickshell > /tmp/quickshell.log 2>&1
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
