# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = systemctl --user start hyprpolkitagent
exec-once = quickshell & vesktop & spotify & thunderbird & hyprpaper & bitwarden-desktop & hypridle & hyprsunset & udiskie
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
