[module/date]
type = internal/date
interval = 1

time = " %a, %b %d %H:%M:%S"
#time-alt = " %H:%M"

format = <label>
format-background = ${colors.bg}
format-foreground = ${colors.fg}
format-padding = 1
format-prefix = %{T1}%{T-}
format-prefix-foreground = ${colors.fg-alt}
label = %{T1}%time%%{T-}
label-active-font = 1
