general {
    before_sleep_cmd = hyprlock
    lock_cmd = hyprlock
}

listener {
    timeout = 540
    on-timeout = brillo -O && brillo -u 200000 -S 0
    on-resume = brillo -u 200000 -I
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
}
