general {
    lock_cmd = pidof hyprlock || hyprlock                                     # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                                  # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'   # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 540
    on-timeout = brillo -O && brillo -u 200000 -S 0
    on-resume = brillo -u 200000 -I
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                            # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'                              # screen on when activity is detected after timeout has fired.
}
