exec-once = hyprsunset

workspace = 1, monitor:eDP-1
workspace = 2, monitor:desc:LG Electronics LG ULTRAGEAR 0x0000A689
workspace = 3, monitor:desc:HP Inc. HP E24 G4 CN43460YQQ

decoration {
    blur {
        enabled = false
    }
}

misc {
    vrr = false
    vfr = true
    render_unfocused_fps = 15
}
