# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrule = workspace 1, match:class ^(vesktop)$
windowrule = workspace 2, match:class ^(kitty)$
windowrule = workspace 7, match:class ^(Bitwarden)$
windowrule = workspace 8, match:class ^(eu.betterbird.Betterbird)$
windowrule = workspace 9, match:class ^(spotify)$

windowrule = render_unfocused on, match:class ^(steam_app_.*)$
