# Execute your favorite apps at launch
# exec-once = waybar & hyprpaper & firefox
exec-once = discord & spotify & thunderbird & flameshot & hyprpaper & dunst & waybar
exec-once=/usr/lib/polkit-kde-authentication-agent-1
