env = WAYLAND_DISPLAY,wayland-1
exec-once = quickshell -p /etc/greetd/quickshell/greetd.qml; hyprctl dispatch exit
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    disable_hyprland_guiutils_check = true
}
