;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

include-file = ~/.config/polybar/modules/workspace.ini
include-file = ~/.config/polybar/modules/colors.ini
include-file = ~/.config/polybar/modules/window.ini
include-file = ~/.config/polybar/modules/filesystem.ini
include-file = ~/.config/polybar/modules/pulseaudio.ini
include-file = ~/.config/polybar/modules/keyboard.ini
include-file = ~/.config/polybar/modules/memory.ini
include-file = ~/.config/polybar/modules/network.ini
include-file = ~/.config/polybar/modules/network-base.ini
include-file = ~/.config/polybar/modules/eth.ini
include-file = ~/.config/polybar/modules/date.ini
include-file = ~/.config/polybar/modules/settings.ini
include-file = ~/.config/polybar/modules/spotify.ini
include-file = ~/.config/polybar/modules/pulseaudio-control.ini
include-file = ~/.config/polybar/modules/battery.ini

include-file = ~/.config//polybar/bars/top.ini
include-file = ~/.config/polybar/bars/bottom.ini
