(setq use-package-always-ensure t)
(setq native-comp-async-report-warnings-errors nil)
(add-hook 'prog-mode-hook (lambda ()
        		    (setq display-line-numbers-type 'relative)
        		    (display-line-numbers-mode 1)))
(scroll-bar-mode -1)
(electric-pair-mode 1)
(tool-bar-mode -1)
(menu-bar-mode -1)
(global-hl-line-mode 1)
(setq vc-follow-symlinks t)
(setq find-file-visit-truename t)
(set-face-attribute 'fixed-pitch nil :family "FiraMono Nerd Font" :height 100)
(set-face-attribute 'variable-pitch nil :family "Linux Libertine O" :height 150)
(add-hook 'text-mode-hook 'variable-pitch-mode)
(global-set-key (kbd "<escape>")      'keyboard-escape-quit)
(setq xref-search-program 'ripgrep)
(setq scroll-preserve-screen-position t)
